import { Link } from "@tanstack/react-router";
import { Mail, MapPin, Phone, Clock, ArrowUpRight } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import "@/styles/ai-studio.css";
import "@/styles/ai-studio-m2.css";
import "@/styles/ai-studio-m4.css";

const linkClass = "upthink-footer-link inline-flex items-center gap-1.5 text-sm text-foreground/80 transition-colors hover:text-[var(--brand-accent)]";
const socialClass = "group grid size-12 place-items-center overflow-hidden border border-border bg-background transition-transform duration-200 hover:-translate-y-1";

export function SiteFooter() {
  const { t } = useI18n();
  return <footer className="upthink-footer border-t border-border bg-background px-6 py-14 sm:px-10 lg:px-16"><div className="mx-auto max-w-7xl">
    <div className="grid grid-cols-1 gap-12 lg:grid-cols-[1.45fr_1fr_1.15fr_1fr_1.2fr] lg:gap-8 xl:gap-12">
      <section><Link to="/" className="mb-5 inline-flex items-center gap-2.5" aria-label="WEARO home"><span className="grid size-9 place-items-center bg-primary font-display text-lg font-bold text-primary-foreground">W</span><span><span className="block font-display text-xl font-semibold uppercase tracking-[0.1em] text-foreground">WEARO<span className="text-[var(--brand-accent)]">.</span></span><span className="block text-[0.58rem] font-semibold uppercase tracking-[0.18em] text-[var(--brand-accent)]">WEAR + OWN / 2026</span></span></Link><p className="max-w-xs text-sm leading-6 text-foreground/75">{t("Thời trang cá nhân hóa với AI Virtual Try-On, AI Personal Stylist và Hybrid Stylist 1:1 — để bạn mặc theo cách của riêng mình.", "Personalized fashion powered by AI Virtual Try-On, AI Personal Stylist and Hybrid Stylist 1:1 — so you can dress your own way.")}</p><div className="mt-7"><p className="mb-2 text-[0.64rem] font-semibold uppercase tracking-[0.18em] text-foreground/60">Newsletter / Member</p><p className="mb-3 text-sm text-foreground/80">{t("Nhận ưu đãi và cập nhật drop mới của WEARO.", "Get offers and updates on the latest WEARO drops.")}</p><form className="flex max-w-sm border-b border-border py-2 focus-within:border-[var(--brand-accent)]" onSubmit={e => e.preventDefault()}><label htmlFor="footer-email" className="sr-only">{t("Email nhận thông tin", "Email address")}</label><input id="footer-email" type="email" placeholder={t("EMAIL CỦA BẠN", "YOUR EMAIL")} className="min-w-0 flex-1 bg-transparent text-xs uppercase tracking-[0.08em] text-foreground outline-none placeholder:text-foreground/45" /><button type="submit" aria-label={t("Đăng ký", "Subscribe")} className="text-foreground transition-colors hover:text-[var(--brand-accent)]"><ArrowUpRight size={18} /></button></form></div></section>
      <section><p className="mb-5 text-[0.68rem] font-semibold uppercase tracking-[0.18em] text-[var(--brand-accent)]">01 / {t("Khám phá", "DISCOVER")}</p><div className="flex flex-col gap-3"><Link to="/shop" className={linkClass}>{t("Sản phẩm", "Products")}</Link><Link to="/shop" className={linkClass}>{t("Hàng mới về", "New Arrivals")}</Link><Link to="/shop" className={linkClass}>{t("Bộ sưu tập", "Collections")}</Link><Link to="/shop" className={linkClass}>{t("Bán chạy", "Best Sellers")}</Link><Link to="/shop" className={linkClass}>Full-Set Looks</Link><Link to="/ai" className={linkClass}>AI Virtual Try-On</Link><Link to="/ai" className={linkClass}>AI Personal Stylist</Link></div></section>
      <section><p className="mb-5 text-[0.68rem] font-semibold uppercase tracking-[0.18em] text-[var(--brand-accent)]">02 / {t("Hỗ trợ", "SUPPORT")}</p><div className="flex flex-col gap-3"><Link to="/about" className={linkClass}>{t("Hướng dẫn mua hàng", "Shopping guide")}</Link><Link to="/checkout" className={linkClass}>{t("Thanh toán", "Payment")}</Link><Link to="/about" className={linkClass}>{t("Đổi trả & hoàn tiền", "Returns & refunds")}</Link><Link to="/about" className={linkClass}>{t("Giao hàng & vận chuyển", "Shipping & delivery")}</Link><Link to="/about" className={linkClass}>{t("Chính sách bảo mật", "Privacy policy")}</Link><Link to="/about" className={linkClass}>{t("Điều khoản dịch vụ", "Terms of service")}</Link></div></section>
      <section><p className="mb-5 text-[0.68rem] font-semibold uppercase tracking-[0.18em] text-[var(--brand-accent)]">03 / {t("Kết nối", "CONNECT")}</p><div className="flex items-center gap-3" aria-label="WEARO social media"><a className={`${socialClass} rounded-[14px]`} href="https://www.instagram.com/upthink.iuh" target="_blank" rel="noreferrer" aria-label="Instagram"><img src="/brand/instagram.svg" alt="" className="size-8 transition-transform duration-200 group-hover:scale-110" /></a><a className={`${socialClass} rounded-full bg-[#1b1a17]`} href="https://www.tiktok.com/@upthink.iuh" target="_blank" rel="noreferrer" aria-label="TikTok"><img src="/brand/tiktok.svg" alt="" className="size-7 transition-transform duration-200 group-hover:scale-110" /></a><a className={`${socialClass} rounded-full`} href="https://www.facebook.com/upthink.iuh" target="_blank" rel="noreferrer" aria-label="Facebook"><img src="/brand/facebook.svg" alt="" className="size-8 transition-transform duration-200 group-hover:scale-110" /></a></div><p className="mt-5 text-sm leading-6 text-foreground/70">{t("Theo dõi WEARO để cập nhật các drop mới, AI styling và lookbook.", "Follow WEARO for new drops, AI styling and lookbook.")}</p></section>
      <section><p className="mb-5 text-[0.68rem] font-semibold uppercase tracking-[0.18em] text-[var(--brand-accent)]">04 / {t("Liên hệ", "CONTACT")}</p><div className="flex flex-col gap-4 text-sm text-foreground/80"><a href="tel:0901246824" className={linkClass}><Phone size={15} /><span><small className="mr-1 text-[0.58rem] uppercase tracking-[0.1em] text-foreground/50">{t("Hotline", "Hotline")}</small>0901 246 824</span></a><a href="mailto:hello@upthink.vn" className={linkClass}><Mail size={15} /><span><small className="mr-1 text-[0.58rem] uppercase tracking-[0.1em] text-foreground/50">Email</small>hello@upthink.vn</span></a><span className="flex items-start gap-1.5 text-sm leading-5"><MapPin size={15} className="mt-0.5 shrink-0" /><span><small className="block text-[0.58rem] uppercase tracking-[0.1em] text-foreground/50">{t("Địa chỉ", "Address")}</small>{t("12 Nguyễn Văn Bảo, Phường Hạnh Thông, TP.HCM", "12 Nguyen Van Bao, Hanh Thong Ward, Ho Chi Minh City")}</span></span><span className="flex items-start gap-1.5 text-sm leading-5"><Clock size={15} className="mt-0.5 shrink-0" /><span><small className="block text-[0.58rem] uppercase tracking-[0.1em] text-foreground/50">{t("Giờ mở cửa", "Opening hours")}</small>{t("Thứ 2 — Chủ Nhật / 08:00 — 22:00", "Monday — Sunday / 08:00 — 22:00")}</span></span></div></section>
    </div>
    <div className="mt-12 border-t border-border pt-6"><div className="flex flex-col gap-5 text-xs text-foreground/60 lg:flex-row lg:items-center lg:justify-between"><p>{t("© 2026 WEARO — Đại học Công nghiệp TP.HCM / IUH. Bảo lưu mọi quyền.", "© 2026 WEARO — Industrial University of Ho Chi Minh City / IUH. All rights reserved.")}</p><div className="flex flex-wrap items-center gap-5"><div className="flex items-center gap-2 uppercase tracking-[0.12em]"><span className="text-[0.58rem] text-foreground/45">{t("Thanh toán", "Payment")}</span><span className="border border-border px-2 py-1">COD</span><span className="border border-border px-2 py-1">VIETQR</span><span className="border border-border px-2 py-1">MOMO</span></div><span className="border-l border-border pl-5 uppercase tracking-[0.1em]">{t("VNĐ / VI", "USD / EN")}</span><span className="border-l border-border pl-5 uppercase tracking-[0.1em] text-foreground/45">Powered by UpThink</span></div></div></div>
  </div></footer>;
}