import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useMemo, useRef, useState } from "react";
import { ArrowRight, Check, Loader2, Menu, RefreshCw, Sparkles, Trash2, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";
import { PRODUCTS, formatVnd } from "@/data/products";
import { generateConcept, generateTryOn, getTryOnJob, listAiProducts } from "@/lib/ai.functions";
import { useCart } from "@/lib/cart";

export const Route = createFileRoute("/ai")({
  validateSearch: (search: Record<string, unknown>): { product?: string } =>
    typeof search["product"] === "string" ? { product: search["product"] } : {},
  head: () => ({ meta: [
    { title: "AI Lab — Concept & Virtual Try-On | WEARO" },
    { name: "description", content: "Tạo concept outfit bằng AI và thử đồ ảo trên ảnh của bạn trước khi mua tại WEARO." },
    { property: "og:title", content: "WEARO AI Lab" },
    { property: "og:description", content: "Concept AI và Virtual Try-On cho thời trang cá nhân hóa tại WEARO." },
  ] }),
  component: AiPage,
});

const STYLES = ["Street", "Minimal", "Smart casual", "Y2K"];
const OCCASIONS = ["Đi học", "Đi làm", "Hẹn hò", "Đi chơi"];

type ProductVariant = { size: string; color: string; stock: number };
type AiProduct = { id: string; name: string; category: string; price: number; image: string; defaultVariant: { size: string; color: string }; variants: ProductVariant[] };
type AiMode = "concept" | "tryon";
type TryOnResult = { image: string; text: string };

function AiPage() {
  const search = Route.useSearch();
  const [consentAccepted, setConsentAccepted] = useState(false);
  const [mode, setMode] = useState<AiMode>(search.product ? "tryon" : "concept");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  if (!consentAccepted) return <AiConsentGate onContinue={() => setConsentAccepted(true)} />;
  const selectMode = (nextMode: AiMode) => { setMode(nextMode); setSidebarOpen(false); };
  return (
    <div className="min-h-screen bg-background">
      <SiteNav />
      <main className="mx-auto w-full max-w-[1600px] px-4 pb-24 pt-24 sm:px-8 sm:pt-28">
        <div className="ai-dashboard-topbar">
          <div>
            <p className="eyebrow">AI Experience · Beta</p>
            <h1 className="mt-2 text-3xl leading-none sm:text-4xl">AI <span className="text-primary">Dashboard</span></h1>
            <p className="mt-2 max-w-2xl text-xs leading-5 text-silver sm:text-[13px]">Một workspace cho AI Stylist, Concept và Virtual Try-On — tập trung vào input và kết quả.</p>
          </div>
          <span className="ai-dashboard-status"><span className="size-1.5 rounded-full bg-[var(--wearo-coral)]" />AI Studio / Ready</span>
        </div>
        <div className="mb-4 flex items-center justify-between gap-4 lg:hidden">
          <div><p className="text-[10px] uppercase tracking-[0.2em] text-primary">Workspace navigation</p><p className="mt-1 text-xs text-silver">New Look / Recent Looks</p></div>
          <button type="button" aria-label="Mở AI dashboard menu" aria-expanded={sidebarOpen} onClick={() => setSidebarOpen(true)} className="inline-flex size-11 items-center justify-center border border-border bg-card text-foreground transition-colors hover:border-primary"><Menu className="size-4" /></button>
        </div>
        <div className="ai-dashboard-shell">
          <div className="ai-dashboard-panel p-3"><AiSidebar /></div>
          {sidebarOpen && <div className="fixed inset-0 z-50 lg:hidden" role="dialog" aria-modal="true"><button type="button" aria-label="Đóng AI dashboard menu" onClick={() => setSidebarOpen(false)} className="absolute inset-0 bg-background/75 backdrop-blur-[2px]" /><aside className="relative h-full w-[min(84vw,320px)] border-r border-border bg-card p-4 shadow-2xl"><div className="mb-5 flex items-center justify-between border-b border-border pb-4"><div><p className="text-xs uppercase tracking-[0.2em] text-primary">AI Dashboard</p><p className="mt-1 text-[11px] text-silver">WEARO / AI Lab</p></div><button type="button" aria-label="Đóng menu" onClick={() => setSidebarOpen(false)} className="inline-flex size-9 items-center justify-center border border-border text-silver hover:border-primary hover:text-foreground"><X className="size-4" /></button></div><AiSidebar mobile /></aside></div>}
          <section className="min-w-0">
            <div className="mb-4 flex items-end justify-between gap-4 border-b border-border pb-4"><div><p className="text-[10px] uppercase tracking-[0.18em] text-primary">02 / Workspace</p><h2 className="mt-1 text-lg font-medium text-foreground sm:text-xl">{mode === "concept" ? "AI Stylist & Concept" : "Virtual Try-On"}</h2></div><span className="hidden text-[9px] uppercase tracking-[0.16em] text-silver sm:block">{mode === "concept" ? "Creative direction" : "Product simulation"}</span></div>
            <div className="mb-4 flex gap-2">{(["concept", "tryon"] as const).map((m) => <button key={m} type="button" onClick={() => selectMode(m)} className={`border px-4 py-2 text-[10px] uppercase tracking-[0.15em] transition-all ${mode === m ? "border-primary bg-primary text-primary-foreground" : "border-border text-beige hover:border-primary hover:text-primary"}`}>{m === "concept" ? "Concept AI" : "Virtual Try-On"}</button>)}</div>
            <div className="min-w-0">{mode === "concept" ? <ConceptWorkspace /> : <TryOnWorkspace initialProduct={search.product} />}</div>
          </section>
        </div>
        <p className="mx-auto mt-5 max-w-2xl text-center text-[11px] leading-5 text-silver">Kết quả AI mang tính tham khảo. Hình ảnh có thể khác với sản phẩm thực tế.</p>
      </main>
      <SiteFooter />
    </div>
  );
}

function AiSidebar({ mobile = false }: { mobile?: boolean }) {
  return <aside className={`${mobile ? "w-full" : "sticky top-24"} min-w-0`}>
    {!mobile && <div className="mb-3 border-b border-border pb-4"><p className="text-xs uppercase tracking-[0.2em] text-primary">AI Dashboard</p><p className="mt-1 text-[11px] text-silver">Concept / Try-On / Looks</p></div>}
    <button type="button" className="mb-3 flex w-full items-center justify-between border border-primary/70 bg-background px-3 py-3 text-left text-xs uppercase tracking-[0.15em] text-primary"><span>+ New Look</span><span className="text-[10px]">⌘ N</span></button>
    <div className="mt-5 border-t border-border pt-5"><p className="mb-2 px-3 text-[10px] uppercase tracking-[0.2em] text-silver">Recent Looks</p><div className="border border-border bg-card px-3 py-3"><p className="text-xs text-beige">No saved looks yet.</p><p className="mt-1 text-[10px] leading-5 text-silver">Lịch sử look sẽ được kết nối với Supabase ở bước tiếp theo.</p></div></div>
    <div className="mt-7 border-t border-border pt-5"><Link to="/shop" className="block px-3 text-[10px] uppercase tracking-[0.18em] text-silver hover:text-primary">← Back to Shop</Link></div>
  </aside>;
}

function AiConsentGate({ onContinue }: { onContinue: () => void }) {
  const [checked, setChecked] = useState(false); const [step, setStep] = useState<1 | 2>(1);
  const rules = [{ title: "Quyền sử dụng ảnh", text: "Chỉ tải lên hình ảnh bạn có quyền sử dụng hoặc đã được người trong ảnh cho phép." }, { title: "Không vi phạm pháp luật", text: "Không dùng AI Studio để tạo nội dung vi phạm pháp luật, xâm phạm quyền riêng tư, danh dự hoặc quyền sở hữu trí tuệ." }, { title: "Kết quả chỉ mang tính tham khảo", text: "Hình ảnh thử đồ có thể khác sản phẩm thực tế về kích thước, màu sắc hoặc độ vừa vặn." }, { title: "Trách nhiệm nội dung", text: "Không tải ảnh chứa thông tin nhạy cảm nếu không cần thiết. Bạn chịu trách nhiệm về nội dung cung cấp." }, { title: "Xác nhận đồng ý", text: "Khi tiếp tục, bạn xác nhận đã đọc, hiểu và chấp hành các quy định sử dụng AI Studio." }];
  const visibleRules = step === 1 ? rules.slice(0, 2) : rules.slice(2);
  return <div className="min-h-screen overflow-x-hidden bg-background"><SiteNav /><main className="flex min-h-[calc(100vh-5rem)] w-full items-center justify-center px-3 py-8 sm:px-8 sm:py-14"><section className="ai-consent-panel w-full">{step === 2 && <button type="button" onClick={() => setStep(1)} className="ai-consent-back">← Quay lại</button>}<p className="eyebrow">AI Experience · Notice</p><h1 className="mt-3 font-semibold text-primary">Quy định sử dụng AI Studio</h1><p className="mt-3 text-sm leading-6 text-beige sm:text-[15px]">{step === 1 ? "Đọc nhanh 2 quy định đầu, rồi bấm Đọc tiếp để xem phần còn lại và xác nhận." : "Đọc xong các quy định cuối, tick xác nhận rồi bấm Tiếp tục."}</p><div key={step} className="mt-6 space-y-4 sm:mt-7 sm:space-y-5" style={{ animation: "aiConsentFade 0.35s ease-out" }}>{visibleRules.map((rule, idx) => { const num = step === 1 ? idx + 1 : idx + 3; return <div key={num} className="flex gap-3"><span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-border text-[11px] font-medium text-primary">{num}</span><div className="min-w-0 flex-1"><p className="text-sm font-medium leading-5 text-foreground">{rule.title}</p><p className="mt-1 text-[13px] leading-5 text-silver sm:text-sm sm:leading-6">{rule.text}</p></div></div>; })}</div>{step === 1 ? <button type="button" onClick={() => setStep(2)} className="mt-7 inline-flex min-h-11 items-center gap-2 text-sm font-medium text-primary transition-opacity hover:opacity-80 sm:mt-8">Đọc tiếp <ArrowRight className="size-4" /></button> : <><label className="ai-consent-check mt-7 sm:mt-8"><input type="checkbox" checked={checked} onChange={(e) => setChecked(e.target.checked)} /><span>Tôi đã đọc và chấp hành các quy định sử dụng AI Studio.</span></label><button type="button" disabled={!checked} onClick={onContinue} className="mt-5 flex h-12 w-full items-center justify-center bg-primary text-xs font-medium uppercase tracking-[0.16em] text-primary-foreground transition-opacity disabled:cursor-not-allowed disabled:opacity-40">Tiếp tục</button></>}<p className="mt-5 text-center text-[11px] leading-5 text-silver sm:mt-6">Bạn có thể rời trang này bất cứ lúc nào.</p></section></main><style>{`@keyframes aiConsentFade { from { opacity: 0; transform: translateX(12px); } to { opacity: 1; transform: translateX(0); } }`}</style></div>;
}

function ResultFrame({ image, pending, emptyLabel, emptyHint }: { image?: string; pending: boolean; emptyLabel: string; emptyHint?: string }) {
  return <div className="flex min-h-[360px] w-full items-center justify-center overflow-hidden bg-background p-4 sm:min-h-[480px] sm:p-8">{pending ? <div className="flex flex-col items-center gap-4 px-6 text-center"><Loader2 className="size-8 animate-spin text-primary" /><div><p className="text-sm font-medium text-foreground">AI đang tạo hình ảnh</p><p className="mt-1.5 text-xs leading-5 text-silver">Quá trình có thể mất vài giây đến hơn một phút. Vui lòng đợi.</p></div></div> : image ? <img src={image} alt="Kết quả AI" className="max-h-[600px] w-full rounded-sm object-contain" /> : <div className="max-w-sm px-6 text-center"><div className="mx-auto mb-4 flex size-12 items-center justify-center rounded-full border border-border bg-card"><Sparkles className="size-5 text-primary" /></div><p className="text-xs uppercase tracking-[0.16em] text-silver">AI result</p><p className="mt-3 text-[15px] leading-6 text-beige">{emptyLabel}</p>{emptyHint && <p className="mt-2 text-xs leading-5 text-silver">{emptyHint}</p>}</div>}</div>;
}

function ConceptWorkspace() {
  const run = useServerFn(generateConcept); const { items } = useCart();
  const [style, setStyle] = useState(STYLES[0]!); const [occasion, setOccasion] = useState(OCCASIONS[0]!); const [prompt, setPrompt] = useState(""); const [query, setQuery] = useState<string | null>(null); const textRef = useRef<HTMLTextAreaElement>(null);
  const cartProducts = useMemo(() => { const seen = new Set<string>(); return items.map((i) => i.product).filter((p) => (seen.has(p.id) ? false : (seen.add(p.id), true))); }, [items]);
  const suggestions = useMemo(() => { const pool = [...cartProducts, ...PRODUCTS.filter((p) => !cartProducts.some((c) => c.id === p.id))]; const q = (query ?? "").toLowerCase(); return pool.filter((p) => p.name.toLowerCase().includes(q)).slice(0, 6); }, [cartProducts, query]);
  const mentions = useMemo(() => PRODUCTS.filter((p) => prompt.includes(`@${p.name}`)).map((p) => p.id), [prompt]);
  const mutation = useMutation({ mutationFn: () => run({ data: { style, occasion, prompt: prompt || undefined, mentions: mentions.length ? mentions : undefined } }), onError: (e: Error) => toast.error(e.message) });
  const onPromptChange = (value: string) => { setPrompt(value); const caret = textRef.current?.selectionStart ?? value.length; const match = /@([^@\n]{0,30})$/.exec(value.slice(0, caret)); setQuery(match ? match[1]! : null); };
  const insertMention = (name: string) => { const el = textRef.current; const caret = el?.selectionStart ?? prompt.length; const before = prompt.slice(0, caret).replace(/@([^@\n]{0,30})$/, ""); const next = `${before}@${name} ${prompt.slice(caret)}`; setPrompt(next); setQuery(null); requestAnimationFrame(() => { el?.focus(); const pos = before.length + name.length + 2; el?.setSelectionRange(pos, pos); }); };
  return <div className="ai-workspace-grid">
    <div className="ai-workspace-input order-1 overflow-hidden border border-border bg-card">
      <div className="border-b border-border p-4 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><div><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-medium uppercase tracking-[0.18em] text-silver">01 · Phong cách</span><span className="text-[10px] text-primary">{style}</span></div><div className="flex flex-wrap gap-2">{STYLES.map((o) => <ChoiceChip key={o} value={o} active={o === style} onClick={() => setStyle(o)} />)}</div></div><div><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-medium uppercase tracking-[0.18em] text-silver">02 · Dịp</span><span className="text-[10px] text-primary">{occasion}</span></div><div className="flex flex-wrap gap-2">{OCCASIONS.map((o) => <ChoiceChip key={o} value={o} active={o === occasion} onClick={() => setOccasion(o)} />)}</div></div></div>
      {cartProducts.length > 0 && <div className="mt-5 border-t border-border pt-4"><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-medium uppercase tracking-[0.18em] text-silver">03 · Sản phẩm context</span><span className="text-[10px] text-silver">Từ giỏ hàng</span></div><div className="flex flex-wrap gap-2">{cartProducts.map((p) => <button key={p.id} type="button" onClick={() => insertMention(p.name)} className="flex items-center gap-2 rounded-full border border-border px-3 py-1.5 text-xs text-beige hover:border-primary"><img src={p.image} alt="" className="size-5 rounded-full object-cover" /><span className="text-primary">@</span>{p.name}</button>)}</div></div>}
      <div className="mt-5 border-t border-border pt-4"><div className="mb-2 flex items-center justify-between"><label htmlFor="ai-stylist-brief" className="text-[10px] font-medium uppercase tracking-[0.18em] text-silver">04 · MÔ TẢ OUTFIT</label><span className={`text-[10px] ${prompt.length >= 540 ? "text-primary" : "text-silver"}`}>{prompt.length}/600</span></div><div className="relative rounded-2xl border border-border bg-background p-2 focus-within:border-primary"><textarea id="ai-stylist-brief" ref={textRef} rows={4} maxLength={600} value={prompt} onChange={(e) => onPromptChange(e.target.value)} placeholder="Mô tả outfit bạn muốn… Ví dụ: tông đen trắng, form rộng, phối @Shadow Hoodie với sneaker trắng." className="w-full resize-none bg-transparent px-3 py-2 text-sm leading-6 text-foreground outline-none placeholder:text-silver" />{query !== null && suggestions.length > 0 && <ul className="absolute inset-x-2 top-full z-30 mt-2 max-h-56 overflow-auto rounded-xl border border-border bg-card shadow-xl">{suggestions.map((p) => <li key={p.id}><button type="button" onMouseDown={(e) => e.preventDefault()} onClick={() => insertMention(p.name)} className="flex w-full items-center gap-3 px-3 py-2 text-left text-sm text-beige hover:bg-background"><img src={p.image} alt="" className="size-8 object-cover" /><span>{p.name}</span></button></li>)}</ul>}<div className="flex flex-col gap-3 border-t border-border px-2 pt-2 sm:flex-row sm:items-center sm:justify-between"><span className="text-[10px] text-silver">{mentions.length > 0 ? `${mentions.length} sản phẩm được nhắc` : "AI sẽ dựa trên style + dịp + brief của bạn"}</span><button type="button" onClick={() => mutation.mutate()} disabled={mutation.isPending} className="min-h-11 rounded-full bg-primary px-6 text-xs font-medium uppercase tracking-[0.14em] text-primary-foreground disabled:opacity-50"><span className="inline-flex items-center gap-2"><Sparkles className="size-3.5" />{mutation.isPending ? "Đang tạo…" : "Tạo concept"}</span></button></div></div></div>
    </div>
    <div className="ai-workspace-result order-2 overflow-hidden border border-border bg-card"><ResultFrame image={mutation.data?.image} pending={mutation.isPending} emptyLabel="Concept outfit của bạn sẽ hiện ở đây." emptyHint="Chọn phong cách + dịp, viết mô tả ngắn rồi bấm Tạo concept." />{mutation.data?.text && <p className="border-t border-border px-4 py-4 text-sm leading-6 text-beige">{mutation.data.text}</p>}</div>
  </div>;
}

function TryOnWorkspace({ initialProduct }: { initialProduct?: string }) {
  const run = useServerFn(generateTryOn); const getJob = useServerFn(getTryOnJob); const listProducts = useServerFn(listAiProducts); const { add } = useCart();
  const fileRef = useRef<HTMLInputElement>(null); const [person, setPerson] = useState<string | null>(null); const [fileName, setFileName] = useState(""); const [productId, setProductId] = useState(initialProduct ?? ""); const [note, setNote] = useState(""); const [selectedVariants, setSelectedVariants] = useState<Record<string, { size: string; color: string }>>({}); const [savedLook, setSavedLook] = useState(false);
  const productsQuery = useQuery({ queryKey: ["ai-products"], queryFn: () => listProducts(), staleTime: 60_000 }); const products = (productsQuery.data ?? []) as AiProduct[]; const product = products.find((p) => p.id === productId) ?? products[0];
  const currentVariant = product ? (() => { const stored = selectedVariants[product.id]; const fallback = product.defaultVariant; const candidate = stored ?? fallback; const valid = product.variants.find((v) => v.size === candidate.size && v.color === candidate.color && v.stock > 0); return valid ? { size: valid.size, color: valid.color } : { size: fallback.size, color: fallback.color }; })() : null;
  const availableSizes = useMemo(() => product ? [...new Set(product.variants.filter((v) => v.stock > 0).map((v) => v.size))] : [], [product]);
  const availableColors = useMemo(() => product ? [...new Set(product.variants.filter((v) => v.stock > 0).filter((v) => v.size === currentVariant?.size).map((v) => v.color))] : [], [product, currentVariant?.size]);
  const selectedStock = product && currentVariant ? product.variants.find((v) => v.size === currentVariant.size && v.color === currentVariant.color)?.stock ?? 0 : 0;
  const mutation = useMutation<TryOnResult, Error>({ mutationFn: async () => { const created = await run({ data: { personImage: person!, productId: product!.id, note: note || undefined } }); for (let attempt = 0; attempt < 60; attempt += 1) { const job = await getJob({ data: { jobId: created.jobId } }); if (job.status === "completed" && job.image) return { image: job.image, text: job.text }; await new Promise((resolve) => setTimeout(resolve, 2000)); } throw new Error("AI đang xử lý lâu hơn dự kiến. Vui lòng thử lại sau ít phút."); }, onError: (e: Error) => toast.error(e.message) });
  const onFileChange = (file: File | undefined) => { if (!file) return; const allowed = ["image/jpeg", "image/png", "image/webp"]; if (!allowed.includes(file.type)) { toast.error("Chỉ hỗ trợ JPG, PNG hoặc WEBP."); return; } if (file.size > 6 * 1024 * 1024) { toast.error("Ảnh tối đa 6MB."); return; } const reader = new FileReader(); reader.onload = () => { setPerson(typeof reader.result === "string" ? reader.result : null); setFileName(file.name); mutation.reset(); setSavedLook(false); }; reader.onerror = () => toast.error("Không thể đọc ảnh. Vui lòng thử lại."); reader.readAsDataURL(file); };
  const clearPerson = () => { setPerson(null); setFileName(""); mutation.reset(); setSavedLook(false); if (fileRef.current) fileRef.current.value = ""; };
  const selectProduct = (id: string) => { setProductId(id); mutation.reset(); setSavedLook(false); };
  const setVariant = (size: string, color?: string) => { if (!product) return; const nextColor = color ?? product.variants.find((v) => v.size === size && v.stock > 0)?.color ?? currentVariant?.color ?? ""; const valid = product.variants.find((v) => v.size === size && v.color === nextColor && v.stock > 0); if (!valid) return; setSelectedVariants((prev) => ({ ...prev, [product.id]: { size: valid.size, color: valid.color } })); mutation.reset(); setSavedLook(false); };
  const setColor = (color: string) => { if (product && currentVariant) setVariant(currentVariant.size, color); };
  const retry = () => { if (person && product && currentVariant && selectedStock > 0) mutation.mutate(); };
  const changeItem = () => { document.getElementById("tryon-product-title")?.scrollIntoView({ behavior: "smooth", block: "center" }); };
  const saveLook = () => { if (!mutation.data?.image || !product || !currentVariant) return; try { const key = "wearo.ai.savedLooks"; const existing = JSON.parse(localStorage.getItem(key) ?? "[]") as unknown[]; existing.unshift({ productId: product.id, productName: product.name, image: mutation.data.image, size: currentVariant.size, color: currentVariant.color, savedAt: new Date().toISOString() }); localStorage.setItem(key, JSON.stringify(existing.slice(0, 12))); setSavedLook(true); toast.success("Đã lưu look trên thiết bị này."); } catch { toast.error("Không thể lưu look trên thiết bị này."); } };
  const addLookToCart = () => { if (!product || !currentVariant || selectedStock <= 0) return; add({ productId: product.id, size: currentVariant.size, color: currentVariant.color, qty: 1 }); toast.success("Đã thêm look vào giỏ hàng."); };
  if (productsQuery.isLoading) return <div className="overflow-hidden border border-border bg-card"><ResultFrame pending={true} emptyLabel="" /><div className="border-t border-border p-5 text-center text-xs text-silver">Đang đồng bộ sản phẩm đã xuất bản từ Supabase…</div></div>;
  if (productsQuery.isError) return <div className="overflow-hidden border border-border bg-card"><ResultFrame pending={false} emptyLabel="Không thể tải danh sách sản phẩm thử đồ." emptyHint="Hãy thử tải lại workspace." /><div className="flex flex-wrap items-center justify-center gap-3 border-t border-border p-5"><button type="button" onClick={() => productsQuery.refetch()} className="inline-flex min-h-10 items-center gap-2 border border-primary px-4 text-xs uppercase tracking-[0.12em] text-primary hover:bg-primary hover:text-primary-foreground"><RefreshCw className="size-3.5" />Tải lại</button><Link to="/shop" className="inline-flex min-h-10 items-center border border-border px-4 text-xs uppercase tracking-[0.12em] text-beige hover:border-primary">Về shop</Link></div></div>;
  if (!product) return <div className="overflow-hidden border border-border bg-card"><ResultFrame pending={false} emptyLabel="Chưa có sản phẩm phù hợp để thử đồ." emptyHint="Cần sản phẩm đã xuất bản, đang hoạt động và có hình ảnh + biến thể." /><div className="border-t border-border p-5 text-center"><Link to="/shop" className="inline-flex min-h-10 items-center border border-primary px-4 text-xs uppercase tracking-[0.12em] text-primary hover:bg-primary hover:text-primary-foreground">Xem sản phẩm</Link></div></div>;
  const resultReady = Boolean(mutation.data?.image); const selectedVariantLabel = currentVariant ? `${currentVariant.size} · ${currentVariant.color}` : "Chưa chọn";
  return <div className="ai-workspace-grid">
    <div className="ai-workspace-input order-1 overflow-hidden border border-border bg-card">
      <div className="border-b border-border p-4 sm:p-6">
        <section className="mb-6" aria-labelledby="tryon-photo-title"><div className="mb-3 flex items-start justify-between gap-3"><div><p id="tryon-photo-title" className="text-[10px] font-medium uppercase tracking-[0.18em] text-primary">01 · Ảnh của bạn</p><p className="mt-1 text-xs leading-5 text-silver">Dùng ảnh rõ, đủ người và không bị che khuất để AI nhận diện tốt hơn.</p></div>{person && <span className="inline-flex shrink-0 items-center gap-1 text-[10px] uppercase tracking-[0.14em] text-primary"><Check className="size-3" />Sẵn sàng</span>}</div>{person ? <div className="flex flex-col gap-3 rounded-2xl border border-border bg-background p-3 sm:flex-row sm:items-center"><img src={person} alt="Ảnh người dùng đã tải lên" className="h-48 w-full rounded-xl object-cover sm:h-28 sm:w-24" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-foreground">{fileName || "Ảnh đã tải lên"}</p><p className="mt-1 text-xs text-silver">JPG, PNG hoặc WebP · tối đa 6MB</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => fileRef.current?.click()} className="inline-flex min-h-9 items-center gap-2 border border-border px-3 text-[10px] uppercase tracking-[0.12em] text-beige hover:border-primary"><Upload className="size-3.5" />Đổi ảnh</button><button type="button" onClick={clearPerson} className="inline-flex min-h-9 items-center gap-2 border border-border px-3 text-[10px] uppercase tracking-[0.12em] text-silver hover:border-primary hover:text-foreground"><Trash2 className="size-3.5" />Xóa</button></div></div></div> : <button type="button" onClick={() => fileRef.current?.click()} className="flex min-h-32 w-full items-center justify-center gap-3 rounded-2xl border border-dashed border-border bg-background px-5 py-6 text-left transition-colors hover:border-primary hover:bg-primary/5"><span className="flex size-10 items-center justify-center rounded-full border border-border"><Upload className="size-4 text-primary" /></span><span><strong className="block text-sm text-foreground">TẢI ẢNH TOÀN THÂN</strong><span className="mt-1 block text-xs text-silver">JPG, PNG hoặc WebP · tối đa 6MB</span></span></button>}<input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(e) => { onFileChange(e.target.files?.[0]); e.currentTarget.value = ""; }} /></section>
        <section className="mb-6" aria-labelledby="tryon-product-title"><div className="mb-3 flex items-end justify-between gap-3"><div><p id="tryon-product-title" className="text-[10px] font-medium uppercase tracking-[0.18em] text-primary">02 · Chọn sản phẩm</p><p className="mt-1 text-xs leading-5 text-silver">Sản phẩm lấy trực tiếp từ danh sách AI đã xuất bản.</p></div><span className="text-[10px] uppercase tracking-[0.12em] text-silver">{products.length} sản phẩm</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{products.map((p) => <button key={p.id} type="button" onClick={() => selectProduct(p.id)} aria-pressed={p.id === product.id} className={`group overflow-hidden rounded-xl border text-left transition-all ${p.id === product.id ? "border-primary ring-1 ring-primary" : "border-border hover:border-primary/60"}`}><div className="relative aspect-[4/5] overflow-hidden bg-background"><img src={p.image} alt={p.name} className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-[1.03]" />{p.id === product.id && <span className="absolute right-2 top-2 inline-flex items-center gap-1 rounded-full bg-primary px-2 py-1 text-[9px] font-semibold uppercase tracking-[0.12em] text-primary-foreground"><Check className="size-2.5" />Đang chọn</span>}</div><div className="p-3"><p className="truncate text-xs font-medium text-foreground">{p.name}</p><p className="mt-1 text-xs text-primary">{formatVnd(p.price)}</p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-silver">{p.category}</p></div></button>)}</div></section>
        <section className="mb-6" aria-labelledby="tryon-variant-title"><div className="mb-3 flex items-end justify-between gap-3"><div><p id="tryon-variant-title" className="text-[10px] font-medium uppercase tracking-[0.18em] text-primary">03 · Chọn biến thể</p><p className="mt-1 text-xs leading-5 text-silver">Chỉ hiển thị size/màu đang còn hàng cho sản phẩm này.</p></div><span className={`text-[10px] uppercase tracking-[0.12em] ${selectedStock > 0 ? "text-primary" : "text-silver"}`}>{selectedStock > 0 ? `${selectedStock} sản phẩm còn hàng` : "Hết hàng"}</span></div><div className="grid gap-4 sm:grid-cols-2"><div><p className="mb-2 text-[10px] uppercase tracking-[0.14em] text-silver">Size</p><div className="flex flex-wrap gap-2">{availableSizes.map((size) => <button key={size} type="button" onClick={() => setVariant(size)} className={`min-w-12 rounded-lg border px-3 py-2 text-xs ${currentVariant?.size === size ? "border-primary bg-primary text-primary-foreground" : "border-border text-beige hover:border-primary"}`}>{size}</button>)}</div></div><div><p className="mb-2 text-[10px] uppercase tracking-[0.14em] text-silver">Color</p><div className="flex flex-wrap gap-2">{availableColors.map((color) => <button key={color} type="button" onClick={() => setColor(color)} className={`rounded-lg border px-3 py-2 text-xs ${currentVariant?.color === color ? "border-primary bg-primary text-primary-foreground" : "border-border text-beige hover:border-primary"}`}>{color}</button>)}</div></div></div><div className="mt-3 flex items-center justify-between rounded-xl border border-border bg-background px-3 py-2.5"><span className="text-[10px] uppercase tracking-[0.12em] text-silver">Đã chọn</span><span className="text-xs font-medium text-foreground">{selectedVariantLabel}</span></div></section>
        <section className="mb-5" aria-labelledby="tryon-note-title"><div className="mb-2 flex items-center justify-between gap-3"><label id="tryon-note-title" htmlFor="tryon-note" className="text-[10px] font-medium uppercase tracking-[0.18em] text-silver">04 · GHI CHÚ</label><span className={`text-[10px] ${note.length >= 360 ? "text-primary" : "text-silver"}`}>{note.length}/400</span></div><div className="rounded-2xl border border-border bg-background p-2 focus-within:border-primary"><textarea id="tryon-note" rows={3} value={note} onChange={(e) => setNote(e.target.value)} maxLength={400} placeholder="Ví dụ: giữ nguyên màu sắc, form hơi rộng, ưu tiên dáng tự nhiên…" className="w-full resize-none bg-transparent px-3 py-2 text-sm leading-6 text-foreground outline-none placeholder:text-silver" /></div></section>
        <button type="button" onClick={() => person && selectedStock > 0 ? mutation.mutate() : toast.error(!person ? "Hãy tải ảnh toàn thân trước." : "Vui lòng chọn biến thể còn hàng.")} disabled={mutation.isPending || !person || selectedStock <= 0} className="flex min-h-14 w-full items-center justify-center gap-2 rounded-xl bg-primary px-6 text-sm font-semibold uppercase tracking-[0.12em] text-primary-foreground transition-transform hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50"><Sparkles className="size-4" />{mutation.isPending ? "Đang thử đồ…" : "BẮT ĐẦU THỬ ĐỒ ẢO"}</button>
      </div>
    </div>
    <div className="ai-workspace-result order-2 overflow-hidden border border-border bg-card"><ResultFrame image={mutation.data?.image} pending={mutation.isPending} emptyLabel="Tải ảnh của bạn và chọn sản phẩm để xem kết quả thử đồ." emptyHint="Ảnh toàn thân sẽ cho kết quả chính xác hơn." />
      {mutation.isError && <div className="border-t border-border bg-primary/5 px-4 py-3 sm:px-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-medium text-foreground">Không thể tạo kết quả thử đồ.</p><p className="mt-1 text-[11px] leading-5 text-silver">Kiểm tra ảnh, sản phẩm đã chọn hoặc thử lại. Không có dữ liệu đơn hàng nào được thay đổi.</p></div><button type="button" onClick={retry} disabled={!person || mutation.isPending || selectedStock <= 0} className="inline-flex min-h-10 shrink-0 items-center justify-center gap-2 border border-primary px-4 text-xs uppercase tracking-[0.12em] text-primary hover:bg-primary hover:text-primary-foreground disabled:opacity-40"><RefreshCw className="size-3.5" />Thử lại</button></div></div>}
      {resultReady && <div className="ai-result-actions border-t border-border p-4 sm:p-5"><div className="mb-3 flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.18em] text-primary">WEARO / AI RESULT</p><p className="mt-1 text-sm font-medium text-foreground">{product.name}</p></div>{savedLook && <span className="text-[10px] uppercase tracking-[0.12em] text-primary">✓ Đã lưu</span>}</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><button type="button" onClick={saveLook} className="min-h-10 border border-border px-3 text-[10px] font-medium uppercase tracking-[0.12em] text-beige hover:border-primary">{savedLook ? "ĐÃ LƯU LOOK" : "SAVE LOOK"}</button><button type="button" onClick={retry} disabled={mutation.isPending || selectedStock <= 0} className="inline-flex min-h-10 items-center justify-center gap-2 border border-border px-3 text-[10px] font-medium uppercase tracking-[0.12em] text-beige hover:border-primary disabled:opacity-40"><RefreshCw className="size-3.5" />TRY AGAIN</button><button type="button" onClick={changeItem} className="min-h-10 border border-border px-3 text-[10px] font-medium uppercase tracking-[0.12em] text-beige hover:border-primary">CHANGE ITEM</button><Link to="/cart" className="inline-flex min-h-10 items-center justify-center border border-primary bg-primary px-3 text-[10px] font-semibold uppercase tracking-[0.12em] text-primary-foreground">VIEW CART</Link></div><div className="mt-3 flex flex-col gap-2 border-t border-border pt-3 sm:flex-row sm:items-center sm:justify-between"><span className="text-xs text-silver">{formatVnd(product.price)} · {selectedVariantLabel} · {selectedStock} còn hàng</span><div className="flex flex-wrap gap-2"><Link to="/product/$id" params={{ id: product.id }} className="border border-border px-3 py-2 text-[10px] uppercase tracking-[0.12em] text-beige hover:border-primary">CHI TIẾT</Link><button type="button" onClick={addLookToCart} disabled={selectedStock <= 0} className="bg-primary px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.12em] text-primary-foreground disabled:opacity-40">THÊM LOOK VÀO GIỎ</button></div></div></div>}
    </div>
  </div>;
}

function ChoiceChip({ value, active, onClick }: { value: string; active: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`rounded-full border px-3 py-1.5 text-[11px] transition-colors ${active ? "border-primary bg-primary/10 text-primary" : "border-border text-silver hover:text-foreground"}`}>{value}</button>; }
