/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AiRouteImport } from './routes/ai'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountWishlistRouteImport } from './routes/account/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAiStudioRouteImport } from './routes/admin/ai-studio'
import { Route as AdminAppearanceRouteImport } from './routes/admin/appearance'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminDesignSystemRouteImport } from './routes/admin/design-system'
import { Route as AdminProductsRouteRouteImport } from './routes/admin/products/route'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AiAssistantRouteImport } from './routes/ai/assistant'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as CheckoutMastercardRouteImport } from './routes/checkout/mastercard'
import { Route as CheckoutMomoRouteImport } from './routes/checkout/momo'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AccountOrdersIdRouteImport } from './routes/account/orders/$id'
import { Route as AdminAppearanceIndexRouteImport } from './routes/admin/appearance/index'
import { Route as AdminAppearanceContentRouteImport } from './routes/admin/appearance/content'
import { Route as AdminAppearanceLibraryRouteImport } from './routes/admin/appearance/library'
import { Route as AdminAppearanceWorkflowRouteImport } from './routes/admin/appearance/workflow'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin/inventory/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductsIdRouteRouteImport } from './routes/admin/products/$id/route'
import { Route as AdminProductsNewRouteRouteImport } from './routes/admin/products/new/route'
import { Route as ApiAdminAiTryOnRouteImport } from './routes/api/admin/ai-try-on'
import { Route as ApiMastercardCreateRouteImport } from './routes/api/mastercard/create'
import { Route as ApiMastercardStatusRouteImport } from './routes/api/mastercard/status'
import { Route as ApiMomoCreateRouteImport } from './routes/api/momo/create'
import { Route as ApiMomoIpnRouteImport } from './routes/api/momo/ipn'
import { Route as ApiOrdersHistoryRouteImport } from './routes/api/orders/history'
import { Route as ApiSepayWebhookRouteImport } from './routes/api/sepay/webhook'
import { Route as AdminProductsIdTagsRouteImport } from './routes/admin/products/$id/tags'
import { Route as ApiTryOnInternalJobsIndexRouteImport } from './routes/api/try-on/internal/jobs/index'
import { Route as ApiTryOnInternalJobsIdRouteImport } from './routes/api/try-on/internal/jobs/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAiStudioRoute = AdminAiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppearanceRoute = AdminAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDesignSystemRoute = AdminDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRouteRoute = AdminProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AiRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutMastercardRoute = CheckoutMastercardRouteImport.update({
  id: '/mastercard',
  path: '/mastercard',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutMomoRoute = CheckoutMomoRouteImport.update({
  id: '/momo',
  path: '/momo',
  getParentRoute: () => CheckoutRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AdminAppearanceIndexRoute = AdminAppearanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAppearanceRoute,
} as any)
const AdminAppearanceContentRoute = AdminAppearanceContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminAppearanceRoute,
} as any)
const AdminAppearanceLibraryRoute = AdminAppearanceLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminAppearanceRoute,
} as any)
const AdminAppearanceWorkflowRoute = AdminAppearanceWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AdminAppearanceRoute,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRouteRoute,
} as any)
const AdminProductsIdRouteRoute = AdminProductsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRouteRoute,
} as any)
const AdminProductsNewRouteRoute = AdminProductsNewRouteRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRouteRoute,
} as any)
const ApiAdminAiTryOnRoute = ApiAdminAiTryOnRouteImport.update({
  id: '/api/admin/ai-try-on',
  path: '/api/admin/ai-try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMastercardCreateRoute = ApiMastercardCreateRouteImport.update({
  id: '/api/mastercard/create',
  path: '/api/mastercard/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMastercardStatusRoute = ApiMastercardStatusRouteImport.update({
  id: '/api/mastercard/status',
  path: '/api/mastercard/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMomoCreateRoute = ApiMomoCreateRouteImport.update({
  id: '/api/momo/create',
  path: '/api/momo/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMomoIpnRoute = ApiMomoIpnRouteImport.update({
  id: '/api/momo/ipn',
  path: '/api/momo/ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersHistoryRoute = ApiOrdersHistoryRouteImport.update({
  id: '/api/orders/history',
  path: '/api/orders/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSepayWebhookRoute = ApiSepayWebhookRouteImport.update({
  id: '/api/sepay/webhook',
  path: '/api/sepay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIdTagsRoute = AdminProductsIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminProductsIdRouteRoute,
} as any)
const ApiTryOnInternalJobsIndexRoute =
  ApiTryOnInternalJobsIndexRouteImport.update({
    id: '/api/try-on/internal/jobs/',
    path: '/api/try-on/internal/jobs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTryOnInternalJobsIdRoute = ApiTryOnInternalJobsIdRouteImport.update({
  id: '/api/try-on/internal/jobs/$id',
  path: '/api/try-on/internal/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/products': typeof AdminProductsRouteRouteWithChildren
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/ai-studio': typeof AdminAiStudioRoute
  '/admin/appearance': typeof AdminAppearanceRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/design-system': typeof AdminDesignSystemRoute
  '/admin/tags': typeof AdminTagsRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/mastercard': typeof CheckoutMastercardRoute
  '/checkout/momo': typeof CheckoutMomoRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRouteRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRouteRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/admin/appearance/content': typeof AdminAppearanceContentRoute
  '/admin/appearance/library': typeof AdminAppearanceLibraryRoute
  '/admin/appearance/workflow': typeof AdminAppearanceWorkflowRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/admin/ai-try-on': typeof ApiAdminAiTryOnRoute
  '/api/mastercard/create': typeof ApiMastercardCreateRoute
  '/api/mastercard/status': typeof ApiMastercardStatusRoute
  '/api/momo/create': typeof ApiMomoCreateRoute
  '/api/momo/ipn': typeof ApiMomoIpnRoute
  '/api/orders/history': typeof ApiOrdersHistoryRoute
  '/api/sepay/webhook': typeof ApiSepayWebhookRoute
  '/admin/appearance/': typeof AdminAppearanceIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/products/$id/tags': typeof AdminProductsIdTagsRoute
  '/api/try-on/internal/jobs/$id': typeof ApiTryOnInternalJobsIdRoute
  '/api/try-on/internal/jobs/': typeof ApiTryOnInternalJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/ai-studio': typeof AdminAiStudioRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/design-system': typeof AdminDesignSystemRoute
  '/admin/tags': typeof AdminTagsRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/mastercard': typeof CheckoutMastercardRoute
  '/checkout/momo': typeof CheckoutMomoRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRouteRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRouteRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/admin/appearance/content': typeof AdminAppearanceContentRoute
  '/admin/appearance/library': typeof AdminAppearanceLibraryRoute
  '/admin/appearance/workflow': typeof AdminAppearanceWorkflowRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/admin/ai-try-on': typeof ApiAdminAiTryOnRoute
  '/api/mastercard/create': typeof ApiMastercardCreateRoute
  '/api/mastercard/status': typeof ApiMastercardStatusRoute
  '/api/momo/create': typeof ApiMomoCreateRoute
  '/api/momo/ipn': typeof ApiMomoIpnRoute
  '/api/orders/history': typeof ApiOrdersHistoryRoute
  '/api/sepay/webhook': typeof ApiSepayWebhookRoute
  '/admin/appearance': typeof AdminAppearanceIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/products/$id/tags': typeof AdminProductsIdTagsRoute
  '/api/try-on/internal/jobs/$id': typeof ApiTryOnInternalJobsIdRoute
  '/api/try-on/internal/jobs': typeof ApiTryOnInternalJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/products': typeof AdminProductsRouteRouteWithChildren
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/ai-studio': typeof AdminAiStudioRoute
  '/admin/appearance': typeof AdminAppearanceRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/design-system': typeof AdminDesignSystemRoute
  '/admin/tags': typeof AdminTagsRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/mastercard': typeof CheckoutMastercardRoute
  '/checkout/momo': typeof CheckoutMomoRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRouteRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRouteRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/admin/appearance/content': typeof AdminAppearanceContentRoute
  '/admin/appearance/library': typeof AdminAppearanceLibraryRoute
  '/admin/appearance/workflow': typeof AdminAppearanceWorkflowRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/admin/ai-try-on': typeof ApiAdminAiTryOnRoute
  '/api/mastercard/create': typeof ApiMastercardCreateRoute
  '/api/mastercard/status': typeof ApiMastercardStatusRoute
  '/api/momo/create': typeof ApiMomoCreateRoute
  '/api/momo/ipn': typeof ApiMomoIpnRoute
  '/api/orders/history': typeof ApiOrdersHistoryRoute
  '/api/sepay/webhook': typeof ApiSepayWebhookRoute
  '/admin/appearance/': typeof AdminAppearanceIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/products/$id/tags': typeof AdminProductsIdTagsRoute
  '/api/try-on/internal/jobs/$id': typeof ApiTryOnInternalJobsIdRoute
  '/api/try-on/internal/jobs/': typeof ApiTryOnInternalJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/ai'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/sitemap.xml'
    | '/track-order'
    | '/admin/products'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/ai-studio'
    | '/admin/appearance'
    | '/admin/content'
    | '/admin/design-system'
    | '/admin/tags'
    | '/ai/assistant'
    | '/api/health'
    | '/checkout/mastercard'
    | '/checkout/momo'
    | '/product/$id'
    | '/admin/'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders/$id'
    | '/admin/appearance/content'
    | '/admin/appearance/library'
    | '/admin/appearance/workflow'
    | '/admin/orders/$id'
    | '/api/admin/ai-try-on'
    | '/api/mastercard/create'
    | '/api/mastercard/status'
    | '/api/momo/create'
    | '/api/momo/ipn'
    | '/api/orders/history'
    | '/api/sepay/webhook'
    | '/admin/appearance/'
    | '/admin/inventory/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/products/$id/tags'
    | '/api/try-on/internal/jobs/$id'
    | '/api/try-on/internal/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/ai'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/sitemap.xml'
    | '/track-order'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/ai-studio'
    | '/admin/content'
    | '/admin/design-system'
    | '/admin/tags'
    | '/ai/assistant'
    | '/api/health'
    | '/checkout/mastercard'
    | '/checkout/momo'
    | '/product/$id'
    | '/admin'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders/$id'
    | '/admin/appearance/content'
    | '/admin/appearance/library'
    | '/admin/appearance/workflow'
    | '/admin/orders/$id'
    | '/api/admin/ai-try-on'
    | '/api/mastercard/create'
    | '/api/mastercard/status'
    | '/api/momo/create'
    | '/api/momo/ipn'
    | '/api/orders/history'
    | '/api/sepay/webhook'
    | '/admin/appearance'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/products/$id/tags'
    | '/api/try-on/internal/jobs/$id'
    | '/api/try-on/internal/jobs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/ai'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/sitemap.xml'
    | '/track-order'
    | '/admin/products'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/ai-studio'
    | '/admin/appearance'
    | '/admin/content'
    | '/admin/design-system'
    | '/admin/tags'
    | '/ai/assistant'
    | '/api/health'
    | '/checkout/mastercard'
    | '/checkout/momo'
    | '/product/$id'
    | '/admin/'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders/$id'
    | '/admin/appearance/content'
    | '/admin/appearance/library'
    | '/admin/appearance/workflow'
    | '/admin/orders/$id'
    | '/api/admin/ai-try-on'
    | '/api/mastercard/create'
    | '/api/mastercard/status'
    | '/api/momo/create'
    | '/api/momo/ipn'
    | '/api/orders/history'
    | '/api/sepay/webhook'
    | '/admin/appearance/'
    | '/admin/inventory/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/products/$id/tags'
    | '/api/try-on/internal/jobs/$id'
    | '/api/try-on/internal/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AiRoute: typeof AiRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackOrderRoute: typeof TrackOrderRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiAdminAiTryOnRoute: typeof ApiAdminAiTryOnRoute
  ApiMastercardCreateRoute: typeof ApiMastercardCreateRoute
  ApiMastercardStatusRoute: typeof ApiMastercardStatusRoute
  ApiMomoCreateRoute: typeof ApiMomoCreateRoute
  ApiMomoIpnRoute: typeof ApiMomoIpnRoute
  ApiOrdersHistoryRoute: typeof ApiOrdersHistoryRoute
  ApiSepayWebhookRoute: typeof ApiSepayWebhookRoute
  ApiTryOnInternalJobsIdRoute: typeof ApiTryOnInternalJobsIdRoute
  ApiTryOnInternalJobsIndexRoute: typeof ApiTryOnInternalJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ai-studio': {
      id: '/admin/ai-studio'
      path: '/ai-studio'
      fullPath: '/admin/ai-studio'
      preLoaderRoute: typeof AdminAiStudioRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appearance': {
      id: '/admin/appearance'
      path: '/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AdminAppearanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/design-system': {
      id: '/admin/design-system'
      path: '/design-system'
      fullPath: '/admin/design-system'
      preLoaderRoute: typeof AdminDesignSystemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/ai/assistant': {
      id: '/ai/assistant'
      path: '/assistant'
      fullPath: '/ai/assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof AiRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/mastercard': {
      id: '/checkout/mastercard'
      path: '/mastercard'
      fullPath: '/checkout/mastercard'
      preLoaderRoute: typeof CheckoutMastercardRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/momo': {
      id: '/checkout/momo'
      path: '/momo'
      fullPath: '/checkout/momo'
      preLoaderRoute: typeof CheckoutMomoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/admin/appearance/': {
      id: '/admin/appearance/'
      path: '/'
      fullPath: '/admin/appearance/'
      preLoaderRoute: typeof AdminAppearanceIndexRouteImport
      parentRoute: typeof AdminAppearanceRoute
    }
    '/admin/appearance/content': {
      id: '/admin/appearance/content'
      path: '/content'
      fullPath: '/admin/appearance/content'
      preLoaderRoute: typeof AdminAppearanceContentRouteImport
      parentRoute: typeof AdminAppearanceRoute
    }
    '/admin/appearance/library': {
      id: '/admin/appearance/library'
      path: '/library'
      fullPath: '/admin/appearance/library'
      preLoaderRoute: typeof AdminAppearanceLibraryRouteImport
      parentRoute: typeof AdminAppearanceRoute
    }
    '/admin/appearance/workflow': {
      id: '/admin/appearance/workflow'
      path: '/workflow'
      fullPath: '/admin/appearance/workflow'
      preLoaderRoute: typeof AdminAppearanceWorkflowRouteImport
      parentRoute: typeof AdminAppearanceRoute
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRouteRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteRouteImport
      parentRoute: typeof AdminProductsRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteRouteImport
      parentRoute: typeof AdminProductsRouteRoute
    }
    '/api/admin/ai-try-on': {
      id: '/api/admin/ai-try-on'
      path: '/api/admin/ai-try-on'
      fullPath: '/api/admin/ai-try-on'
      preLoaderRoute: typeof ApiAdminAiTryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mastercard/create': {
      id: '/api/mastercard/create'
      path: '/api/mastercard/create'
      fullPath: '/api/mastercard/create'
      preLoaderRoute: typeof ApiMastercardCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mastercard/status': {
      id: '/api/mastercard/status'
      path: '/api/mastercard/status'
      fullPath: '/api/mastercard/status'
      preLoaderRoute: typeof ApiMastercardStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/momo/create': {
      id: '/api/momo/create'
      path: '/api/momo/create'
      fullPath: '/api/momo/create'
      preLoaderRoute: typeof ApiMomoCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/momo/ipn': {
      id: '/api/momo/ipn'
      path: '/api/momo/ipn'
      fullPath: '/api/momo/ipn'
      preLoaderRoute: typeof ApiMomoIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/history': {
      id: '/api/orders/history'
      path: '/api/orders/history'
      fullPath: '/api/orders/history'
      preLoaderRoute: typeof ApiOrdersHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sepay/webhook': {
      id: '/api/sepay/webhook'
      path: '/api/sepay/webhook'
      fullPath: '/api/sepay/webhook'
      preLoaderRoute: typeof ApiSepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$id/tags': {
      id: '/admin/products/$id/tags'
      path: '/tags'
      fullPath: '/admin/products/$id/tags'
      preLoaderRoute: typeof AdminProductsIdTagsRouteImport
      parentRoute: typeof AdminProductsIdRouteRoute
    }
    '/api/try-on/internal/jobs/': {
      id: '/api/try-on/internal/jobs/'
      path: '/api/try-on/internal/jobs'
      fullPath: '/api/try-on/internal/jobs/'
      preLoaderRoute: typeof ApiTryOnInternalJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/try-on/internal/jobs/$id': {
      id: '/api/try-on/internal/jobs/$id'
      path: '/api/try-on/internal/jobs/$id'
      fullPath: '/api/try-on/internal/jobs/$id'
      preLoaderRoute: typeof ApiTryOnInternalJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminProductsIdRouteRouteChildren {
  AdminProductsIdTagsRoute: typeof AdminProductsIdTagsRoute
}

const AdminProductsIdRouteRouteChildren: AdminProductsIdRouteRouteChildren = {
  AdminProductsIdTagsRoute: AdminProductsIdTagsRoute,
}

const AdminProductsIdRouteRouteWithChildren =
  AdminProductsIdRouteRoute._addFileChildren(AdminProductsIdRouteRouteChildren)

interface AdminProductsRouteRouteChildren {
  AdminProductsIdRouteRoute: typeof AdminProductsIdRouteRouteWithChildren
  AdminProductsNewRouteRoute: typeof AdminProductsNewRouteRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteRouteChildren: AdminProductsRouteRouteChildren = {
  AdminProductsIdRouteRoute: AdminProductsIdRouteRouteWithChildren,
  AdminProductsNewRouteRoute: AdminProductsNewRouteRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteRouteWithChildren =
  AdminProductsRouteRoute._addFileChildren(AdminProductsRouteRouteChildren)

interface AdminAppearanceRouteChildren {
  AdminAppearanceContentRoute: typeof AdminAppearanceContentRoute
  AdminAppearanceLibraryRoute: typeof AdminAppearanceLibraryRoute
  AdminAppearanceWorkflowRoute: typeof AdminAppearanceWorkflowRoute
  AdminAppearanceIndexRoute: typeof AdminAppearanceIndexRoute
}

const AdminAppearanceRouteChildren: AdminAppearanceRouteChildren = {
  AdminAppearanceContentRoute: AdminAppearanceContentRoute,
  AdminAppearanceLibraryRoute: AdminAppearanceLibraryRoute,
  AdminAppearanceWorkflowRoute: AdminAppearanceWorkflowRoute,
  AdminAppearanceIndexRoute: AdminAppearanceIndexRoute,
}

const AdminAppearanceRouteWithChildren = AdminAppearanceRoute._addFileChildren(
  AdminAppearanceRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminProductsRouteRoute: typeof AdminProductsRouteRouteWithChildren
  AdminAiStudioRoute: typeof AdminAiStudioRoute
  AdminAppearanceRoute: typeof AdminAppearanceRouteWithChildren
  AdminContentRoute: typeof AdminContentRoute
  AdminDesignSystemRoute: typeof AdminDesignSystemRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminProductsRouteRoute: AdminProductsRouteRouteWithChildren,
  AdminAiStudioRoute: AdminAiStudioRoute,
  AdminAppearanceRoute: AdminAppearanceRouteWithChildren,
  AdminContentRoute: AdminContentRoute,
  AdminDesignSystemRoute: AdminDesignSystemRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AccountOrdersRouteChildren {
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersIdRoute: AccountOrdersIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountWishlistRoute: typeof AccountWishlistRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountWishlistRoute: AccountWishlistRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AiRouteChildren {
  AiAssistantRoute: typeof AiAssistantRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiAssistantRoute: AiAssistantRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface CheckoutRouteChildren {
  CheckoutMastercardRoute: typeof CheckoutMastercardRoute
  CheckoutMomoRoute: typeof CheckoutMomoRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutMastercardRoute: CheckoutMastercardRoute,
  CheckoutMomoRoute: CheckoutMomoRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AiRoute: AiRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackOrderRoute: TrackOrderRoute,
  ApiHealthRoute: ApiHealthRoute,
  ProductIdRoute: ProductIdRoute,
  ApiAdminAiTryOnRoute: ApiAdminAiTryOnRoute,
  ApiMastercardCreateRoute: ApiMastercardCreateRoute,
  ApiMastercardStatusRoute: ApiMastercardStatusRoute,
  ApiMomoCreateRoute: ApiMomoCreateRoute,
  ApiMomoIpnRoute: ApiMomoIpnRoute,
  ApiOrdersHistoryRoute: ApiOrdersHistoryRoute,
  ApiSepayWebhookRoute: ApiSepayWebhookRoute,
  ApiTryOnInternalJobsIdRoute: ApiTryOnInternalJobsIdRoute,
  ApiTryOnInternalJobsIndexRoute: ApiTryOnInternalJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
