import { createServerFn } from "@tanstack/react-start";
import { supabaseRequest } from "./supabase.server";

type OrderItemInput = { productId: string; size: string; color: string; quantity: number };
type CreateOrderInput = { customerName: string; phone: string; email?: string; address: string; city: string; district: string; paymentMethod: "cod" | "vietqr" | "momo"; items: OrderItemInput[]; userId?: string; mockUser?: boolean };
export type CustomerOrder = { id:string; order_code:string; customer_name:string; phone:string; email:string|null; address:string; city:string; district:string; payment_method:string; payment_status:string; order_status:string; subtotal:number; shipping_fee:number; total:number; note:string|null; created_at:string; user_id?:string|null };
export type CustomerOrderItem = { id:string; order_id:string; product_id:string; product_name:string; size:string; color:string; quantity:number; unit_price:number; variant_id:string|null; created_at:string };
export type CustomerOrderDetail = CustomerOrder & { items: CustomerOrderItem[] };
type AuthUser = { id:string; email?:string };
function createOrderCode(){const date=new Date().toISOString().slice(0,10).replaceAll("-","");const random=Math.random().toString(36).slice(2,7).toUpperCase();return `FD-${date}-${random}`;}
function getSupabaseAuthConfig(){const url=process.env.SUPABASE_URL;const secretKey=process.env.SUPABASE_SECRET_KEY;if(!url||!secretKey)throw new Error("Thiếu cấu hình Supabase trên server.");return{url,secretKey};}
async function resolveCustomerFromToken(accessToken:string):Promise<AuthUser>{const token=accessToken.trim();if(!token)throw new Error("UNAUTHORIZED");const{url,secretKey}=getSupabaseAuthConfig();const response=await fetch(`${url}/auth/v1/user`,{headers:{apikey:secretKey,Authorization:`Bearer ${token}`}});if(response.status===401||response.status===403)throw new Error("UNAUTHORIZED");if(!response.ok)throw new Error(`Không thể xác minh phiên đăng nhập (${response.status})`);const user=(await response.json()) as AuthUser;if(!user?.id)throw new Error("UNAUTHORIZED");return user;}
function normalizeEmail(email:string|undefined|null){return(email??"").trim().toLowerCase();}
export async function listCustomerOrdersByToken(accessToken:string,options?:{limit?:number;offset?:number}):Promise<CustomerOrder[]>{const user=await resolveCustomerFromToken(accessToken);const email=normalizeEmail(user.email);const limit=Math.min(Math.max(options?.limit??50,1),100);const offset=Math.max(options?.offset??0,0);const select="id,order_code,customer_name,phone,email,address,city,district,payment_method,payment_status,order_status,subtotal,shipping_fee,total,note,created_at";const byUserId=await supabaseRequest<CustomerOrder[]>(`orders?user_id=eq.${encodeURIComponent(user.id)}&select=${select}&order=created_at.desc&limit=${limit}&offset=${offset}`,{method:"GET"}).catch(()=>[] as CustomerOrder[]);let byEmail:CustomerOrder[]=[];if(email)byEmail=await supabaseRequest<CustomerOrder[]>(`orders?email=eq.${encodeURIComponent(email)}&select=${select}&order=created_at.desc&limit=${limit}&offset=${offset}`,{method:"GET"});const map=new Map<string,CustomerOrder>();for(const row of[...byUserId,...byEmail])if(row?.id)map.set(row.id,row);return Array.from(map.values()).sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());}
export async function getCustomerOrderByToken(accessToken:string,orderIdOrCode:string):Promise<CustomerOrderDetail|null>{const user=await resolveCustomerFromToken(accessToken);const email=normalizeEmail(user.email);const key=orderIdOrCode.trim();if(!key)return null;const select="id,order_code,customer_name,phone,email,address,city,district,payment_method,payment_status,order_status,subtotal,shipping_fee,total,note,created_at";let orders=await supabaseRequest<CustomerOrder[]>(`orders?id=eq.${encodeURIComponent(key)}&select=${select}&limit=1`,{method:"GET"}).catch(()=>[] as CustomerOrder[]);if(!orders.length)orders=await supabaseRequest<CustomerOrder[]>(`orders?order_code=eq.${encodeURIComponent(key)}&select=${select}&limit=1`,{method:"GET"});const order=orders[0];if(!order)return null;const ownsByUser=(order as CustomerOrder&{user_id?:string|null}).user_id===user.id;const ownsByEmail=email.length>0&&normalizeEmail(order.email)===email;if(!ownsByUser&&!ownsByEmail)return null;const items=await supabaseRequest<CustomerOrderItem[]>(`order_items?order_id=eq.${encodeURIComponent(order.id)}&select=*&order=created_at.asc`,{method:"GET"}).catch(()=>[] as CustomerOrderItem[]);return{...order,items};}

export const createOrder=createServerFn({method:"POST"}).validator((data:CreateOrderInput)=>data).handler(async({data})=>{
  if(!data.items?.length)throw new Error("Giỏ hàng đang trống.");
  if(!data.customerName||!data.phone||!data.address)throw new Error("Vui lòng nhập đầy đủ thông tin giao hàng.");
  if(!["cod","vietqr","momo"].includes(data.paymentMethod))throw new Error("Phương thức thanh toán không hợp lệ.");
  for(const item of data.items){if(!item.productId||!item.size||!item.color)throw new Error("Thông tin sản phẩm trong giỏ hàng không hợp lệ.");if(!Number.isInteger(item.quantity)||item.quantity<1)throw new Error("Số lượng sản phẩm không hợp lệ.");}
  if(data.mockUser){
    const orderCode=`MOCK-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;
    const totalItems=data.items.reduce((sum,item)=>sum+item.quantity,0);
    return {orderId:`mock-order-${Date.now()}`,orderCode,total:0,mock:true,itemCount:totalItems};
  }
  const orderCode=createOrderCode();
  const body:Record<string,unknown>={p_order_code:orderCode,p_customer_name:data.customerName.trim(),p_phone:data.phone.trim(),p_email:data.email?.trim()||null,p_address:data.address.trim(),p_city:data.city.trim(),p_district:data.district.trim(),p_payment_method:data.paymentMethod,p_items:data.items.map(item=>({productId:item.productId,size:item.size,color:item.color,quantity:item.quantity})),p_note:null};
  if(data.userId?.trim())body.p_user_id=data.userId.trim();
  const result=await supabaseRequest<{order_id:string;order_code:string;total:number}[]>("rpc/create_order_atomic",{method:"POST",body:JSON.stringify(body)});const order=result[0];if(!order)throw new Error("Không thể tạo đơn hàng.");return{orderId:order.order_id,orderCode:order.order_code,total:order.total,mock:false};
});
export const listMyOrders=createServerFn({method:"POST"}).validator((data:{accessToken:string;limit?:number;offset?:number})=>data).handler(async({data})=>{try{return{orders:await listCustomerOrdersByToken(data.accessToken,{limit:data.limit,offset:data.offset})};}catch(error){if(error instanceof Error&&error.message==="UNAUTHORIZED")throw new Error("Vui lòng đăng nhập để xem lịch sử đơn hàng.");throw error;}});
export const getMyOrder=createServerFn({method:"POST"}).validator((data:{accessToken:string;orderIdOrCode:string})=>data).handler(async({data})=>{try{const order=await getCustomerOrderByToken(data.accessToken,data.orderIdOrCode);if(!order)throw new Error("Không tìm thấy đơn hàng.");return{order};}catch(error){if(error instanceof Error&&error.message==="UNAUTHORIZED")throw new Error("Vui lòng đăng nhập để xem đơn hàng.");throw error;}});
